# Generated by Django 6.1.1 on 2026-10-01 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aroha_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
