# Generated by Django 6.1.1 on 2026-10-07 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aroha_app', '0002_remove_user_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senior_name', models.CharField(max_length=150)),
                ('contact_person', models.CharField(max_length=150)),
                ('request_type', models.CharField(choices=[('medicine', 'Medicine / Prescriptions'), ('food', 'Groceries & Meal Assistance'), ('companion', 'Companionship / Check-in'), ('other', 'Other Assistance')], default='other', max_length=20)),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
